language: node_js
node_js:
  - "11"
sudo: required

services:
  - docker

script:
  - sudo docker build . -t rusttest -f testCoverage.Dockerfile
  - sudo docker create -ti --name dummy rusttest bash
  - sudo docker cp dummy:/code/lcov.info -> lcov.info
  - sudo docker rm -fv dummy
  - bash <(curl -s https://codecov.io/bash) -f lcov.info
  - sudo docker pull lambci/lambda:provided
  - npm ci
  - npm test

before_deploy: 
  - node ./src/js/copyBinaries
  - npm install -g serverless
  - sls deploy
    
after_deploy:
  - > 
    body='{"request":{"branch":"master"}}';
    curl -s -X POST \
      -H "Content-Type: application/json" \
      -H "Accept: application/json" \
      -H "Travis-API-Version: 3" \
      -H "Authorization: token ${TRAVIS_TOKEN}" \
      -d "$body" \
      https://api.travis-ci.com/repo/realoptions%2Fmain_site/requests;
    

 deploy:
  - provider: releases
    api_key: $github_token
    file_glob: true
    file:
    - "./target/lambda/release/*"
    - "./serverless.yml"
    - "./docs/openapi_merged.yml"
    skip_cleanup: true
    on:
      repo: realoptions/option_price_faas
      tags: true
      branch: master