language: rust
sudo: required
rust:
- stable
- beta
- nightly

before_install:
- wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
- nvm install 8
- node --version
- rustup target add x86_64-unknown-linux-musl
- git fetch --all # intended for getting tags

script:
  - cd functions
  - cargo build --release --target=x86_64-unknown-linux-musl
  - cargo test
  - cd ..
before_deploy: ###ADD section for kicking off client build!
  - > #ensure only runs once :|
    if  [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      npm install -g serverless;
      sls deploy;
    fi
    
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev

#after_success:
  #- >
  #  if  [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
  #    cd main_site;
  #    bash <(curl -s https://codecov.io/bash);
  #    cd ..
  #  fi
env:
  matrix: ##AWS token for deploying lambdas
    secure: KGHSrpMDZ9OJ3X9tN+7Sbs7OeDnbkimvMwqR8Rj/sYqYDishyEan7pzGdPpjKw2K7sxLyqoiQ8wKO17yd8I4G0IFxGpQkg/UvqkrqU4rQ19mdMwY467jew6pm9rioQ9nc3d8vMDk5CSd4QyK4TfRhaRhGRyCZNsGC1884z5shVDLXNvSM+8EKOrQ+SMoXdEDLWxb+hpvAfRoqVNtX7bb53wRGr4c+TMYrx7kGVSvOgZpVdSc9qeBMziHW/W6dxbyyRHPq9SwyReGZcUodjGZ54cTO43F4ygIpMdY17bnRXEbi5D/crihghiaIH9a626PPUjCkrsmihHr+xzD9VxvdrNe0KL7Yt2QfjqUxt+3KlYJ/aXCPzp+7udCJurSQMs2z5l/hUntP42WSBBlFSWF1HOpRZWXcKVWmsIpRIF+gJvPagcjB+0D+xi3ynD8TSfd2bncerkm/KIP2dsAoCXNA7K7qcMthahVwny8ydJEaGoPVjeGRy8oF1XOaPCv1GaokROMqddjBK8F2PQELicUrGdORRfm9Kvyj5OdLNRbFNWaVyyYn44OL4fGEgfOAM49J0YTKQjwB3ZvLx0pYGAZnThH5mTG4XBOkXdfGlpmdfe2VDqjt7Wp3IRjzRWEhxmD/i2BqB9aKcG5CDMuORLe97PI4p54LCdBrm17s6AANQk=
deploy:
  - provider: releases
    api_key: ##Github token for pushing to releases
      secure: dbSsXp7XBdsrBbW5XtZyyC7fDzFjO2tnUBgpdj7LnML4BmcdPpNWTQ7pEDNU0P0fcQaOc3/NAE7YwDi71uKclo0bZyXfmlzgVOKTkFAuMwrkYMhvM29d2p919ezUVAnfvDSK7U2uT8wucC09sVGbMfdiCC+ep12/O5+3rMfGyeB8A8dIkXx0UwqErqyc8yyxm8S9orpHYGgspDtWUJuEkhUZ3SFQZuwTTKqA79h9b7KaP0/8nMOk8FW1Ck/zzw1fJNy9478EXLYfL8UiAybr1n1eRqWft4o/qHTC2KI9AG2+EvG3XCe/3WLyzWOgH0lst515g6nZybM/eZgxngvQj6egEVUd1GLFaWgC69BksfMvdfr9nd70kfgVqfYiEcCQU1TtSxR1htDphtCs7QDLb0bSLCykHYe6VR0DrE8EZxrmA15WY0/Fbi3DgA46rEP5s0K79NkvuxElC+JhHpMh+ygi36jabBFDr64as/ToVf604iVZiaMddWIi6FIgkdg65JXl7/f2QCUwy2iuxk+gVl7FWtteti++2seyM2xfgyTgxkVrDVQ0L8uN3snkuZkADEJgRGtBe8SyZa90hNs+VNjGUh7Kb9CEJPmmUjSmyXAnrlhW2rKlxbJqoIuaxfoh/XJO4Ma9CWqvZlzTsYwoeW7jjM8aWmIWhCjAAX0juvk=
    file_glob: true
    file:
    - "./functions/target/x86_64-unknown-linux-musl/release/output_constraints"
    - "./functions/target/x86_64-unknown-linux-musl/release/calibrator"
    - "./functions/target/x86_64-unknown-linux-musl/release/pricer"
    - "./lambda/**"
    - "./serverless.yml"
    - "./docs/openapi_merged.yml"
    skip_cleanup: true
    on:
      repo: phillyfan1138/option_price_faas
      tags: true
      rust: 'stable'
