language: rust
sudo: required
rust:
- stable
- beta
- nightly

before_install:
- wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
- nvm install 8
- node --version
- rustup target add x86_64-unknown-linux-musl

script:
  - cd functions
  - cargo build --release --target=x86_64-unknown-linux-musl
  - cargo test
  - cd ..
before_deploy: ###ADD section for kicking off client build!
  - > #ensure only runs once :|
    if  [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      npm install -g serverless;
      sls deploy;
    fi
after_deploy:
  - > #ensure only runs once :|
    if  [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      curl -s -X POST \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        -H "Travis-API-Version: 3" \
        -H "Authorization: token ${TRAVIS_TOKEN}" \
        -d "'{\"request\":{\"branch\":\"master\"}}'" \
        https://api.travis-ci.com/repo/realoptions/main_site/requests;
    fi
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev

deploy:
  - provider: releases
    api_key: ##Github token for pushing to releases
      secure: dbSsXp7XBdsrBbW5XtZyyC7fDzFjO2tnUBgpdj7LnML4BmcdPpNWTQ7pEDNU0P0fcQaOc3/NAE7YwDi71uKclo0bZyXfmlzgVOKTkFAuMwrkYMhvM29d2p919ezUVAnfvDSK7U2uT8wucC09sVGbMfdiCC+ep12/O5+3rMfGyeB8A8dIkXx0UwqErqyc8yyxm8S9orpHYGgspDtWUJuEkhUZ3SFQZuwTTKqA79h9b7KaP0/8nMOk8FW1Ck/zzw1fJNy9478EXLYfL8UiAybr1n1eRqWft4o/qHTC2KI9AG2+EvG3XCe/3WLyzWOgH0lst515g6nZybM/eZgxngvQj6egEVUd1GLFaWgC69BksfMvdfr9nd70kfgVqfYiEcCQU1TtSxR1htDphtCs7QDLb0bSLCykHYe6VR0DrE8EZxrmA15WY0/Fbi3DgA46rEP5s0K79NkvuxElC+JhHpMh+ygi36jabBFDr64as/ToVf604iVZiaMddWIi6FIgkdg65JXl7/f2QCUwy2iuxk+gVl7FWtteti++2seyM2xfgyTgxkVrDVQ0L8uN3snkuZkADEJgRGtBe8SyZa90hNs+VNjGUh7Kb9CEJPmmUjSmyXAnrlhW2rKlxbJqoIuaxfoh/XJO4Ma9CWqvZlzTsYwoeW7jjM8aWmIWhCjAAX0juvk=
    file_glob: true
    file:
    - "./functions/target/x86_64-unknown-linux-musl/release/output_constraints"
    - "./functions/target/x86_64-unknown-linux-musl/release/calibrator"
    - "./functions/target/x86_64-unknown-linux-musl/release/pricer"
    - "./lambda/**"
    - "./serverless.yml"
    - "./docs/openapi_merged.yml"
    skip_cleanup: true
    on:
      repo: phillyfan1138/option_price_faas
      tags: true
      rust: 'stable'
