openapi: 3.0.0
components:
  schemas:
    ErrorResponse:
      properties:
        err:
          type: string
    PostOptionsResponse:
      type: array
      items:
        - type: object
          properties:
            value:
              type: number
            at_point:
              type: number
            iv:
              type: number
          required:
            - value
            - at_point
          additionalProperties: false
    PostOptionsRequest:
      type: object
      properties:
        num_u:
          type: integer
        rate:
          type: number
        maturity:
          type: number
        asset:
          type: number
        cf_parameters:
          type: object
          properties:
            sigma:
              type: number
            c:
              type: number
            g:
              type: number
            m:
              type: number
            'y':
              type: number
            mu_l:
              type: number
            sig_l:
              type: number
            lambda:
              type: number
            speed:
              type: number
            v0:
              type: number
            eta_v:
              type: number
            rho:
              type: number
          additionalProperties: false
        strikes:
          type: array
          items:
            - type: number
        quantile:
          type: number
      required:
        - num_u
        - rate
        - maturity
        - asset
        - cf_parameters
        - strikes
        - quantile
      additionalProperties: false
    PostDensityResponse:
      type: array
      items:
        - type: object
          properties:
            value:
              type: number
            at_point:
              type: number
          required:
            - value
            - at_point
          additionalProperties: false
    PostRiskMetricResponse:
      type: object
      properties:
        value_at_risk:
          type: number
        expected_shortfall:
          type: number
      required:
        - value_at_risk
        - expected_shortfall
      additionalProperties: false
    GetConstraintsResponse:
      type: object
      properties:
        rate:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        asset:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        maturity:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        num_u:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        quantile:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        lambda:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        mu_l:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        sig_l:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        c:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        g:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        m:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        'y':
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        v0:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        speed:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        eta_v:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        sigma:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
        rho:
          type: object
          properties:
            lower:
              type: number
            upper:
              type: number
          required:
            - lower
            - upper
          additionalProperties: false
      additionalProperties: false
  securitySchemes: {}
info:
  title: Option Pricing and Sensitivities
  description: >-
    Option pricing using advanced models such as Heston, Extended Merton, and
    Extended CGMY
  version: '1'
paths:
  '/v1/{model}/calculator/{optionType}/{sensitivity}':
    post:
      operationId: calculator
      summary: Calculator for computing option prices and sensitivities
      description: >-
        Computes European option prices, implied volatilities, and sensitivities
        at every strike price
      responses:
        '200':
          description: Option prices and sensitivites
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostOptionsResponse'
        '400':
          description: An error message for incorrect request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/v1/{model}/density/density':
    post:
      operationId: density
      summary: Calculator for computing probability densities
      description: Computes probability density
      responses:
        '200':
          description: Density
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDensityResponse'
        '400':
          description: An error message for incorrect request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/v1/{model}/density/riskmetric':
    post:
      operationId: riskmetric
      summary: Calculator for computing risk metrics
      description: Computes value at risk and expected shortfall
      responses:
        '200':
          description: Value at risk and expected shortfall
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostRiskMetricResponse'
        '400':
          description: An error message for incorrect request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/v1/{model}/parameters/parameter_ranges':
    get:
      operationId: constraints
      summary: Parameter Constraints
      description: Computes probability density
      responses:
        '200':
          description: Constraints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetConstraintsResponse'
        '400':
          description: An error message for incorrect request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
