service: option-price-faas

provider:
  name: aws
  runtime: nodejs8.10
  stage: prd

package:
  exclude:
    - functions/**
    - node_modules
    - tests/**
    - tests
    - .gitignore
    - package-lock.json
    - package.json
    - README.md
    - serverless.yml
    - .travis.yml
    - docs
  include:
   - functions/target/x86_64-unknown-linux-musl/release/output_constraints
   - functions/target/x86_64-unknown-linux-musl/release/pricer
   - lambda/**
functions:
  calculator:
    handler: lambda/pricer.calculator
    events:
      - http:
          path: v1/{model}/calculator/{optionType}/{sensitivity}
          method: post
          cors: true
          request:
            parameters:
              paths:
                optionType: true
                sensitivity: true
                model: true
              querystrings:
                includeImpliedVolatility: false

  density:
    handler: lambda/pricer.density
    events:
      - http:
          path: v1/{model}/density
          method: post
          cors: true
          request:
            parameters:
              paths:
                model: true

  riskmetric:
    handler: lambda/pricer.riskmetric
    events:
      - http:
          path: v1/{model}/riskmetric
          method: post
          cors: true
          request:
            parameters:
              paths:
                model: true
          
  constraints:
    handler: lambda/pricer.constraints
    events:
      - http:
          path: v1/{model}/parameters/parameter_ranges
          method: get
          cors: true
          request:
            parameters:
              paths:
                model: true