service: option-price-faas

provider:
  name: aws
  runtime: nodejs8.10
  stage: prd
  usagePlan: # Optional usage plan configuration
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100
  #UsagePlanKey:
  #    Type: "AWS::ApiGateway::UsagePlanKey"
  #    Properties:
  #      KeyId:
  #        Ref: ApiGatewayApiKey1
  #      KeyType: API_KEY
  #      UsagePlanId:
  #        Ref: UsagePlan
plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.finside.org
    basePath: realoptions
    stage: ${self:provider.stage}
    createRoute53Record: true

package:
  exclude:
    - functions/**
    - node_modules
    - tests/**
    - tests
    - .gitignore
    - package-lock.json
    - package.json
    - README.md
    - main_site/**
    - serverless.yml
    - .travis.yml
    - docs/**
  include:
   - functions/target/x86_64-unknown-linux-musl/release/output_constraints
   - functions/target/x86_64-unknown-linux-musl/release/pricer
   - lambda/**
functions:
  calculator:
    handler: lambda/pricer.calculator
    events:
      - http:
          path: v1/{model}/calculator/{optionType}/{sensitivity}
          method: post
          cors: true
          private: true
          request:
            parameters:
              paths:
                optionType: true
                sensitivity: true
                model: true
              querystrings:
                includeImpliedVolatility: false

  density:
    handler: lambda/pricer.density
    events:
      - http:
          path: v1/{model}/density
          method: post
          cors: true
          private: true
          request:
            parameters:
              paths:
                model: true

  riskmetric:
    handler: lambda/pricer.riskmetric
    events:
      - http:
          path: v1/{model}/riskmetric
          method: post
          cors: true
          private: true
          request:
            parameters:
              paths:
                model: true
          
  constraints:
    handler: lambda/pricer.constraints
    events:
      - http:
          path: v1/{model}/parameters/parameter_ranges
          method: get
          cors: true
          private: true
          request:
            parameters:
              paths:
                model: true