export const HOME='/home'
export const PRODUCTS='/products'
export const DEVELOPERS='/developers'
export const REGISTER='/register'
export const LOGIN='/login'
export const MARKETPLACE='/tmpmarketplace'
export const SUCCESS_MARKETPLACE='/tmpsuccessmarketplace'
export const SUBSCRIPTIONS='/subscriptions'