[package]
name = "calibrator"
version = "0.1.0"
authors = ["Daniel Stahl <danstahl1138@gmail.com>"]

[dependencies]
#cuckoo = "0.2.0"
fang_oost_option = "0.9.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"