name: deploy
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: test
              run: |
                cargo test
                docker pull lambci/lambda:provided
                npm ci
                npm test

            - name: extract benchmarks
              run: |
                rustup target add x86_64-unknown-linux-musl
                apt-get update
                apt-get install -y gcc
                apt-get install -y musl-tools
                apt-get install -y musl-dev
                apt-get install -y gnuplot
                cargo build --release --target=x86_64-unknown-linux-musl
                cargo bench

            - name: deploy benchmarks to ghpages
              uses: JamesIves/github-pages-deploy-action@master
              env: 
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BRANCH: gh-pages
                FOLDER: target/criterion
                
            - name: deploy aws
              run: |
                node ./src/js/copyBinaries
                npx serverless deploy
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: kickoff main site job
              run: |
                curl -s -X POST \
                  -H "Content-Type: application/json" \
                  -H "Accept: application/vnd.github.everest-preview+json" \
                  -H "Authorization: token  ${{ secrets.ACCESS_TOKEN }}" \
                  -d '{"event_type": "on-demand-test"}'
                  https://api.github.com/repos/realoptions/main_site/dispatches

           