name: release
on:
    release:
        types: [published]

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run cargo test
      run: cargo test
    - uses: phillyfan1138/musl-rust-action@master
    - name: Integration test
      run: |
        docker pull lambci/lambda:provided
        npm ci
        npm test 

    - name: deploy aws
      run: |
        node ./src/js/copyBinaries
        npx serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: release files
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./target/x86_64-unknown-linux-musl/release/*,./serverless.yml,./docs/openapi_merged.yml"
        # bodyFile: "body.md"
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: kickoff main site job
      run: |
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token  ${{ secrets.ACCESS_TOKEN }}" \
          -d '{"event_type": "on-demand-test"}' \
          https://api.github.com/repos/realoptions/main_site/dispatches

    
    