name: release
on:
  push:
    tags:
    - '*'
env:
  PROJECT_ID: finside
  RUN_REGION: us-central1
  SERVICE_NAME: realoptions
jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run cargo test
      run: cargo test

    # Setup gcloud CLI
    # To create a service account, 
    # gcloud iam service-accounts create [SA-NAME] \
    # --description "[SA-DESCRIPTION]" \
    # --display-name "[SA-DISPLAY-NAME]"

    # to create a key for the service account,
    # gcloud iam service-accounts keys create ~/key.json \
    # --iam-account [SA-NAME]@[PROJECT-ID].iam.gserviceaccount.com

    # to base64 it,
    # cat ~/key.json | base64

    # to get email address,
    # gcloud iam service-accounts list

    # to grant roles, 
    # gcloud projects add-iam-policy-binding [project] \
    # --member serviceAccount:[emailaddress] \
    # --role roles/run.admin 
    # gcloud projects add-iam-policy-binding [project] \
    # --member serviceAccount:[emailaddress] \
    # --role roles/viewer
    # gcloud projects add-iam-policy-binding [project] \
    # --member serviceAccount:[emailaddress] \
    # --role roles/cloudbuild.builds.builder
    # gcloud projects add-iam-policy-binding [project] \
    # --member serviceAccount:[emailaddress] \
    # --role roles/iam.serviceAccountUser
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    # Configure gcloud CLI
    - name: gcloud Set up
      run: |
        gcloud config set project $PROJECT_ID
        gcloud config set run/region $RUN_REGION
    # Build and push image to Google Container Registry
    - name: Build
      run: |
        gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
    # Deploy image to Cloud Run
    - name: Deploy
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --allow-unauthenticated
    # Firebase hosting
    - name: Set up firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}