name: release
on:
    release:
        types: [published]

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hecrj/setup-rust-action@master
        with:
          targets: x86_64-unknown-linux-musl
      - name: test
        run: |
          cargo test
          cargo build --release --target=x86_64-unknown-linux-musl
          docker pull lambci/lambda:provided
          npm ci
          npm test

      - name: release files
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./target/x86_64-unknown-linux-musl/release/*,./serverless.yml,./docs/openapi_merged.yml"
          # bodyFile: "body.md"
          token: ${{ secrets.ACCESS_TOKEN }}