name: test
on: [push]

jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          rust: [stable, nightly]

      steps:
      - uses: actions/checkout@v1
      - uses: hecrj/setup-rust-action@master
        with:
          rust-version: ${{ matrix.rust }}

      - name: Build
        run: cargo build

      - name: Run tests stable
        if: matrix.rust == 'stable'
        run: cargo test

      - name: Run tests nightly with coverage
        if: matrix.rust == 'nightly' 
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads
          CRATE_NAME: pricer
        run: |
          cargo test
          curl -L https://github.com/mozilla/grcov/releases/download/v0.5.5/grcov-linux-x86_64.tar.bz2 | tar jxf -
          zip -0 ccov.zip `find . \( -name "${CRATE_NAME}*.gc*" \) -print`
          ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
          bash <(curl -s https://codecov.io/bash) -f lcov.info -t ${{ secrets.CODECOV_TOKEN }}
      - name: Run integration tests
        uses: phillyfan1138/musl-rust-actions@master
        if: matrix.rust == 'stable'
        run: |
          docker pull lambci/lambda:provided
          npm ci
          npm test
