name: test
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: test coverage
              run: |
                docker build . -t rusttest -f testCoverage.Dockerfile
                docker create -ti --name dummy rusttest bash
                docker cp dummy:/code/lcov.info ./
                docker rm -fv dummy
                bash <(curl -s https://codecov.io/bash) -f lcov.info -t ${{ secrets.CODECOV_TOKEN }}
                docker pull lambci/lambda:provided
                npm ci
                npm test